name: CI

on:
  push:
    branches:
      - main # Assure-toi que tu pousses vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SENTRY_AUTH_TOKEN: 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

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Install dependencies
        run: npm install
        # Ajoute des logs ou des messages pour vérifier si l'étape est atteinte
        continue-on-error: false # Arrête le workflow en cas d'échec

      - name: Run lint
        run: npm run lint
        continue-on-error: false

      - name: Run tests
        run: npm run test
        continue-on-error: false
